---
title: "Teaching"
description: "Teaching experience and selected materials"
---

## Teaching philosophy

My core teaching objectives are to teach students how to read and understand political science research, critically evaluate the content they consume, and to apply political science concepts to the real world.

## Instructor of record

### Comparative Electoral Systems · Summer Session 2, 2024

Upper-division undergraduate course covering electoral systems around the world, and the impacts electoral systems have on politics.

- Average instructor rating: **4.64 / 5.0**
- Median instructor rating: **5.0 / 5.0**

Syllabus available upon request

### Selected feedback

> "Super knowledgeable, but not in the way that he makes it complicated to understand. Scates utilizes analogies and real-world examples to make harder topics easier to understand!"

> "I loved the interactive activities as they helped me learn and were really fun. I really enjoyed this class, and I never thought that electoral systems could be so interesting! He did an amazing job teaching this course!!!"

## Teaching assistant

| Course | Terms | Taught sections? |
|---|---|---|
| German Politics | Spring 2026 | N |
| Eastern European Politics | Winter 2024 | Y |
| Politics of Inequality | Spring 2022 | N |
| Comparative Electoral Systems | Spring 2023 | N |
| Development Aid | Winter 2023 | N |
| International Organizations | Winter 2022 | N |
| Scientific Study of War | Fall 2022, Spring 2024 | N |
| Local Politics | Winter 2025 | N |
| America Decides! | Summer Session II 2025 | N |
| Introduction to International Relations | Winter 2024, Fall 2024, Spring 2025, Winter 2026, Spring 2026 | Y |
| Introduction to Comparative Politics | Fall 2023, Fall 2025 | Y |

- Average instructor rating for sections: **4.4 / 5.0**
- Median instructor rating for sections **5.0 / 5.0**

### Selected feedback

> "He really did invite as much discussion as possible, and he delved into questions pretty thoroughly"

> "He knows his stuff very well, so he's great at simplyfying complex subjects into their core components and explaining each very well! Much like the professor, but even more thorough
in my opinion. He spends more time on difficult material as well, and emphasizes the importance of that to the class and on the exams."

> "I could tell Daniel enjoyed international relations and working with students. He was curious about learning more when we asked questions about the course and connected it to other fields
or when we needed more resources to understand the topics. I think he is a great TA and his enthusiasm about the field created an environment conducive to effective learning and curiosity."

> "He seems genuinely excited about the material and topic and can easily explain the relevance of such topics in today's world (especially cause the topic is international relations). He
teaches it in a way where students understand it and find it engaging, fun, and relevant. He's a great TA and deserves a lot of credit for the time and care he puts into his job!"

> "He takes a bunch of his time to just add a bunch of comments on each and every essay he grades. He gives a lot of attention to detail and spends a bunch of energy providing useful
and specific feedback for each and every essay!"

> "Always responds to student emails with much detail answering every single questions at least I've sent out in a very methodical and attentive way! In class as well encouraging questions
and answering them with a smile on his face! Taking some time even after discussion or office hours to answer questions or connect with students! Very friendly and accommodating TA"

> "Daniel is extremely educated on the topic and is enthusiastic to answer questions and help students, regardless of how many times I asked for clarification. For questions I had about class
topics that I connected to other fields, Daniel gave me resources and journals to look at, which spurred curiosity and encouraged my learning"



